{{- if and .Values.js.enabled (and (eq .Values.js.kind "DaemonSet")) -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  {{- if .Values.js.deploymentAnnotations }}
  annotations:
    {{ toYaml .Values.js.deploymentAnnotations }}
  {{- end }}
  labels:
  {{- include "thingsboard.js.labels" . | nindent 4 }}
  name: {{ template "thingsboard.js.fullname" . }}
  {{ include "thingsboard.namespace" . | nindent 2 }}
spec:
  selector:
    matchLabels:
      {{- include "thingsboard.js.matchLabels" . | nindent 6 }}
  {{- if .Values.js.updateStrategy }}
  updateStrategy:
    {{ toYaml .Values.js.updateStrategy }}
  {{- end }}
  template:
    metadata:
      {{- if .Values.js.podAnnotations }}
      annotations:
        {{ toYaml .Values.js.podAnnotations }}
      {{- end }}
      labels:
      {{- include "thingsboard.js.labels" . | nindent 8 }}
      {{- if .Values.js.pod.labels }}
      {{ toYaml .Values.js.pod.labels | indent 8 }}
    {{- end }}
    spec:
      serviceAccountName: {{ template "thingsboard.js.serviceAccount.name" . }}
      {{- if .Values.js.priorityClassName }}
      priorityClassName: "{{ .Values.js.priorityClassName }}"
      {{- end }}
      containers:
        - name: {{ template "thingsboard.name" . }}-{{ .Values.js.name }}
          image: "{{ .Values.js.image.repository }}:{{ template "thingsboard.version" . }}"
          imagePullPolicy: "{{ .Values.js.image.pullPolicy }}"
          resources:
          {{ toYaml .Values.js.resources | indent 2 }}
          {{- if gt (len .Values.js.env) 0 }}
          env:
            {{- range $key, $value := .Values.js.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
          {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml .Values.imagePullSecrets | indent 2 }}
      {{- end }}
      {{- if .Values.js.tolerations }}
      tolerations:
      {{ toYaml .Values.js.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.js.nodeSelector }}
      nodeSelector:
      {{ toYaml .Values.js.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.js.securityContext }}
      securityContext:
      {{ toYaml .Values.js.securityContext | indent 8 }}
      {{- end }}
      {{- if .Values.js.affinity }}
      affinity:
      {{ toYaml .Values.js.affinity | nindent 8 }}
      {{- end }}
  {{- end -}}
