{{- if and .Values.web.enabled (and (eq .Values.web.kind "Deployment")) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- if .Values.web.deploymentAnnotations }}
  annotations:
    {{ toYaml .Values.web.deploymentAnnotations }}
  {{- end }}
  labels:
  {{- include "thingsboard.web.labels" . | nindent 4 }}
  name: {{ template "thingsboard.web.fullname" . }}
  {{ include "thingsboard.namespace" . | nindent 2 }}
spec:
  selector:
    matchLabels:
      {{- include "thingsboard.web.matchLabels" . | nindent 6 }}
  replicas: {{ .Values.web.replicas }}
  template:
    metadata:
      {{- if .Values.web.podAnnotations }}
      annotations:
        {{ toYaml .Values.web.podAnnotations }}
      {{- end }}
      labels:
      {{- include "thingsboard.web.labels" . | nindent 8 }}
      {{- if .Values.web.pod.labels }}
      {{ toYaml .Values.web.pod.labels | indent 8 }}
    {{- end }}
    spec:
      serviceAccountName: {{ template "thingsboard.web.serviceAccount.name" . }}
      {{- if .Values.web.priorityClassName }}
      priorityClassName: "{{ .Values.web.priorityClassName }}"
      {{- end }}
      containers:
        - name: {{ template "thingsboard.name" . }}-{{ .Values.web.name }}
          image: "{{ .Values.web.image.repository }}:{{ template "thingsboard.version" . }}"
          imagePullPolicy: "{{ .Values.web.image.pullPolicy }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /index.html
              port: http
            initialDelaySeconds: {{ .Values.web.livenessProbe.initialDelay }}
            periodSeconds: {{ .Values.web.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.web.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.web.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.web.livenessProbe.successThreshold }}
          resources:
          {{ toYaml .Values.web.resources | indent 2 }}
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/tb-web-ui/conf
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml .Values.imagePullSecrets | indent 2 }}
      {{- end }}
      {{- if .Values.web.tolerations }}
      tolerations:
      {{ toYaml .Values.web.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.web.nodeSelector }}
      nodeSelector:
      {{ toYaml .Values.web.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.web.securityContext }}
      securityContext:
      {{ toYaml .Values.web.securityContext | indent 8 }}
      {{- end }}
      {{- if .Values.web.affinity }}
      affinity:
      {{ toYaml .Values.web.affinity | nindent 8 }}
      {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ if .Values.web.configMapOverrideName }}{{ .Release.Name }}-{{ .Values.web.configMapOverrideName }}{{- else }}{{ template "thingsboard.web.fullname" . }}{{- end }}
{{- end -}}
