{{- if .Values.daemonSet -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "thingsboard-component.fullname" . }}
  labels:
    {{- include "thingsboard-component.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "thingsboard-component.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "thingsboard-component.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "thingsboard-component.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if gt (len .Values.application.config) 0 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "thingsboard-component.fullname" . }}
            items:
            {{- range .Values.application.config }}
            - key: {{ .name }}
              path: {{ .path }}
            {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if gt (len .Values.application.config) 0 }}
          volumeMounts:
          - mountPath: {{ .Values.application.configMountPath }}
            name: config
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: CLUSTER_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TB_HOST
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          {{- if gt (len .Values.application.env) 0 -}}
          {{- toYaml .Values.application.env | nindent 12 }}
          {{- end -}}
          {{- if gt (len .Values.application.ports) 0 }}
          ports:
            {{- range .Values.application.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: {{ .protocol | default "TCP" }}
            {{- end }}
          {{- end }}
          {{- if and .Values.application.probe (gt (len .Values.application.ports) 0) }}
          livenessProbe:
            {{- range .Values.application.ports }}
            {{- if .checkPath }}
            httpGet:
              path: {{ .checkPath }}
              port: {{ .port }}
            {{- else }}
            tcpSocket:
              port: {{ .port }}
            {{- end }}
            {{- end }}
            initialDelaySeconds: {{ .Values.application.healthCheck.initialDelaySeconds }}
            timeoutSeconds: 10
          readinessProbe:
            {{- range .Values.application.ports }}
            {{- if .checkPath }}
            httpGet:
              path: {{ .checkPath }}
              port: {{ .port }}
            {{- else }}
            tcpSocket:
              port: {{ .port }}
            {{- end }}
            {{- end }}
            initialDelaySeconds: {{ .Values.application.healthCheck.initialDelaySeconds }}
            timeoutSeconds: 10
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
{{- end -}}
